---
AWSTemplateFormatVersion: 2010-09-09
Description: App Runner for a public web application
Parameters:
  ProjectName:
    Description: Set the project name.
    Type: String
    Default: webapp
  IamStackName:
    Description: Set the IAM stack name.
    Type: String
    Default: webapp-iam-roles-for-apprunner
  EcrImageName:
    Description: Set the ECR image name.
    Type: String
  EcrImageTag:
    Description: Set the ECR image tag.
    Type: String
    Default: latest
  Cpu:
    Description: Set the number of CPU units reserved.
    Type: String
    Default: 1 vCPU
  Memory:
    Description: Set the amount of memory, in MB or GB, reserved.
    Type: String
    Default: 2 GB
  ImagePort:
    Description: Set the port that the application listens to in the container.
    Type: String
    Default: 8080
Resources:
  AppRunnerObservabilityConfiguration:
    Type: AWS::AppRunner::ObservabilityConfiguration
    Properties:
      ObservabilityConfigurationName: !Sub ${ProjectName}-ar-xray-tracing
      TraceConfiguration:
        Vendor: AWSXRAY
  AppRunnerService:
    Type: AWS::AppRunner::Service
    Properties:
      ServiceName: !Sub ${ProjectName}-ar-service-public
      # AutoScalingConfigurationArn: ''
      HealthCheckConfiguration:
        HealthyThreshold: 1
        Interval: 5
        Path: /
        Protocol: TCP
        Timeout: 2
        UnhealthyThreshold: 5
      InstanceConfiguration:
        Cpu: !Ref Cpu
        Memory: !Ref Memory
        InstanceRoleArn:
          Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-AppRunnerInstanceRole
      ObservabilityConfiguration:
        ObservabilityConfigurationArn: !Ref AppRunnerObservabilityConfiguration
        ObservabilityEnabled: true
      SourceConfiguration:
        AuthenticationConfiguration:
          AccessRoleArn:
            Fn::ImportValue: !Sub ${AWS::Region}-${IamStackName}-AppRunnerECRAccessRole
        AutoDeploymentsEnabled: true
        ImageRepository:
          ImageRepositoryType: ECR
          ImageIdentifier: !Sub ${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/${EcrImageName}:${EcrImageTag}
          ImageConfiguration:
            Port: !Ref ImagePort
            # RuntimeEnvironmentSecrets: []
            # RuntimeEnvironmentVariables: []
            # StartCommand: ''
Outputs:
  AppRunnerServiceId:
    Description: AppRunner Service Id
    Value: !Ref AppRunnerService
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppRunnerService
  AppRunnerServiceUrl:
    Description: AppRunner Service URL
    Value:
      Fn::Join:
        - ''
        - - https://
          - !GetAtt AppRunnerService.ServiceUrl
    Export:
      Name: !Sub ${AWS::Region}-${AWS::StackName}-AppRunnerServiceUrl
